apiVersion: v1
kind: Service
metadata:
  name: reclip
  namespace: reclip
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8899
      targetPort: 8899
      nodePort: 31300
  selector:
    app: reclip
